import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PathImagenesService {
  path:string;
  pathtwiter:string;
  pathin:string;
  pathlog:string;
  pathhome:string;
  pathentrar:string;
  pathcrs:string;
  pathcrs2:string;
  pathbiblioteca:string;
  pathcapacitaciones:string;
  pathpregrado:string;
  pathinvestigacion:string;
  pathmaestria:string;
  pathdoctorado:string;
  pathmision:string;
  pathvision:string;
  pathlogoutm:string;
  pathbibliotecavirtual:string;
  pathpaginacapacitaciones:string;
  pathpaginapregrado:string;
  pathpaginainvestigacion:string;
  pathpaginamaestrias:string;
  pathpaginadoctorados:string;
  pathrecuperarcorreo:string;
  pathavatarperfil:string;
  constructor() { 
    this.path='';
    this.pathtwiter='';
    this.pathin='';
    this.pathlog='';
    this.pathhome='';
    this.pathentrar='';
    this.pathcrs='';
    this.pathcrs2='';
    this.pathbiblioteca='';
    this.pathcapacitaciones='';
    this.pathpregrado='';
    this.pathinvestigacion='';
    this.pathmaestria='';
    this.pathdoctorado='';
    this.pathmision='';
    this.pathvision='';
    this.pathlogoutm='';
    this.pathbibliotecavirtual='';
    this.pathpaginacapacitaciones='';
    this.pathpaginapregrado='';
    this.pathpaginainvestigacion='';
    this.pathpaginamaestrias='';
    this.pathpaginadoctorados='';
    this.pathrecuperarcorreo="";
    this.pathavatarperfil="";
  }
}
